set(EML_ROOT_DIR "/usr/local/")
set(EML_INCLUDE_DIRS "${EML_ROOT_DIR}/include")
set(EML_LIBRARIES "${EML_ROOT_DIR}/lib/libeml.so" "${EML_ROOT_DIR}/lib/libeml.a")
set(EML_FOUND "TRUE")
set(EML_VERSION_MAJOR "1")
set(EML_VERSION_MINOR "0")
